config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :topics do
    resources :posts
  end
  get '/votes/up', to: 'votes#up'
  get '/votes/down', to: 'votes#down'

  resources :comments, except: [:index]
  root to: 'topics#index'
  resources :favorites, only: [:create, :index, :destroy]
  get '/users/comments', to: 'users#comments'
  get '/users/posts', to: 'users#posts'

end

app/models/favorite.rb
# Favorite model
#
# == License
# Code is owned by Kari
# Fields include id, user_id, post_id, status, created_at, updated_at
class Favorite < ActiveRecord::Base
  include Statusable
  belongs_to :user
  belongs_to :post
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!
  before_action :params_exist, only: [:create]

  def index
    @favorites = current_user.favorites.active
  end

  def create
    @post = Post.find(favorite_params[:post_id])
    @favorite = Favorite.new user: current_user, post: @post
    my_save(@favorite, favorites_path)
  end

  def destroy
    @favorite = Favorite.find(params[:id])
    my_destroy(@favorite, favorites_path)
  end

  private

  def params_exist
    # binding.pry
    redirect_to topics_path if params.nil? || params[:favorite].nil?
  end

  def favorite_params
    params.require(:favorite).permit(:post_id)
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_form.html.erb
<%= form_for @favorite do |f| %>
<%= f.select(:post_id, @posts.map{ |v| [v.title, v.id] }) %>
<%= f.submit 'Save' %>
<% end %>

app/views/favorites/index.html.erb
<h2> Favorites Index </h2>
  <% @favorites.each do |fav| %>
    <div class="row">
      <div class="small-10 small-offset-2 columns">
        <h3><%= fav.post.title %></h3>
        <h4><%= fav.post.description %></h4>

        <td><%= link_to "Remove from Favorites", fav, method: :delete, data: {confirm: 'Are you sure?'} %></td>

      </div>
    </div>
  <% end %>

app/views/favorites/new.html.erb
<%= render partial: 'form' %>

app/views/favorites/show.html.erb
<div  class="row" >
    <div class="small-6 columns">
      	<h2><%= @favorite.post.title %></h2>
      	<td><%= @favorite.post.description %></td>
    </div>
    <div class="small-6 columns">
    	<td><%# = link_to "Show", @post %></td>
    	<td><%# = link_to "Edit", edit_topic_post_path(@topic, @post) %></td>
    	<td><%# = link_to "Destroy", @post, method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </div>
  <br class="clear" />
</div>