config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :topics do
    resources :posts
  end
  get '/votes/up', to: 'votes#up'
  get '/votes/down', to: 'votes#down'

  resources :comments, except: [:index]
  root to: 'topics#index'
  resources :favorites, only: [:create, :index, :destroy]
  get '/users/comments', to: 'users#comments'
  get '/users/posts', to: 'users#posts'

end

app/models/topic.rb
# Topic model
#
# == License
# Code is owned by Kari
# Fields include id, title, description,
# status, created_at, updated_at
class Topic < ActiveRecord::Base
  attr_accessor :image
  include Statusable
  has_many :posts
  validates :title, length: { maximum: 255 }, presence: true
  validates :description, length: { maximum: 65_535 }
  mount_uploader :image, ImageUploader
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :user_is_admin, only: [:new, :create, :destroy, :edit, :update]
  before_action :authenticate_user!, only: [:new, :create, :destroy, :edit, :update]
  before_action :get_topic, only: [:show, :destroy, :edit, :update]

  def index
    @topics = Topic.active
  end

  def create
    @topic = Topic.new(topic_params)
    my_save(@topic, topics_path)
  end

  def new
    @topic = Topic.new
  end

  def show
    posts = @topic.posts.active.order('rank desc')
    @posts = posts.paginate(:page => params[:page], :per_page => 5)
  end

  def destroy
    my_destroy(@topic, topics_path)
  end

  def edit
  end

  def update
    my_update(@topic, topic_params, @topic)
  end

  private

  def topic_params
    params.require(:topic).permit(:title, :description, :image)
  end

  def get_topic
    @topic = Topic.active.where(id: params[:id]).first
    if @topic.nil?
      flash[:error] = "Topic does not exist"
      redirect_to topics_path
    end
  end

  def user_is_admin
    unless current_user.is_admin?
      flash[:error] = "Unauthorized User"
      redirect_to topics_path
    end
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def crud_links(object)
    # binding.pry
    return '<td>&nbsp</td>'.html_safe if current_user.nil? || !current_user.is_admin?
    links = ''
    links += "<td>#{ link_to 'Modify', [:edit, object]}</td> "
    links += "<td>#{link_to 'Trash', object, method: :delete, data: { confirm: 'Are you sure?' }}</td>"

    links.html_safe
  end

  def topic_link()
    return '<td> </td>'.html_safe if current_user.nil? || !current_user.is_admin?
    links = ''
    links += "<div class='button success radius'>#{ link_to "New Topic", new_topic_path }</div>"
    links.html_safe
  end

  def new_post(object)
    return '<td> </td>'.html_safe if current_user.nil?
    links = ''
    links += "<div class='button success radius'>#{ link_to "New Post", new_topic_post_path(object) }</div>"
    links.html_safe
  end

  def topic_index(object)
    links = ''
    links << "<div class='button success radius'>#{ link_to "All Topics", topics_path(object) }</div>"
    links.html_safe
  end

  def shorten(object)
    truncate(object, length: 200)
  end

end

app/views/topics/_errors.html.erb
<%= crud_links(@topic) %>

    # binding.pry
    return '<td>&nbsp</td>'.html_safe if current_user.nil? || !current_user.is_admin?

<td><%= link_to 'Modify', [:edit, object]} %></td>
<td><%= link_to 'Trash', object, method: :delete, data: { confirm: 'Are you sure?' } %></td>

    links.html_safe
  end


<%= red_error_box(@topic) %>
<%= form_for @topic, :html => {:multipart => true} do |f| %>
  <%= f.label :title%>
  <%= f.text_field :title %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.file_field :image %>
  <%= f.submit 'Save' %>
<% end %>

app/views/topics/_form.html.erb
<%= red_error_box(@topic) %>
<%= form_for @topic, :html => {:multipart => true} do |f| %>
  <%= f.label :title%>
  <%= f.text_field :title %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.file_field :image %>
  <%= f.submit 'Save' %>
<% end %>

app/views/topics/edit.html.erb
<%= form_for @topic do |f| %>
  <%= f.label :title%>
  <%= f.text_field :title %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.submit 'Submit' %>
<% end %>

app/views/topics/index.html.erb
<div class="row show-topics">
  <div class="small-10 columns small-centered">
    <section class="row">
        <h4 class="model-title"> Topics </h4>


        <div class="row">
        <% @topics.each do |topic| %>
             <div class="small-4 columns">
             <%= link_to topic.title, topic_path(topic) %>
              </div>
              <div class="small-4 columns">
                <%= topic.posts.count %> posts
              </div>
             <div class="small-4 columns">
              <%= crud_links(topic) %>
             </div>
          <% end %>
          <%= topic_link() %>
        </div>
    </section>
  </div>
</div>

app/views/topics/new.html.erb
<%= render partial: 'form' %>

app/views/topics/show.html.erb
<div class="row show-topics">
  <div class="small-10 columns small-centered">
    <section class="row">
      <div class="small-3 columns">
        	<h2><%= @topic.title %></h2>
          <%= crud_links(@topic) %>
      </div>
      <div class="small-6 columns">
        	<h4><%= @topic.description %></h4>
          <%= image_tag @topic.image_url.to_s %>
      </div>
      <div class="small-3 columns">
          <h5><%= new_post(@topic) %><%= topic_index(@topic) %></h5>
      </div>
    </section>


      	<% @posts.each do |post| %>
        <section class="row post-list">
          <div class="small-6 columns">

            <h3><%= post.rank.to_i %>&nbsp<%= link_to post.title, topic_post_path(@topic, post) %></h3>
            <h5><%= post.created_at.strftime("%d %b. %Y") %><%= vote_link(post) %></h5><%= image_tag post.image_url.to_s %><%= crud_post(post) %>
          </div>
          <div class="small-6 columns">

            <h4><%= shorten(post.description) %></h4>
          </div>
        </section>
            <% end %>
        <%= will_paginate @posts %>

  </div>
  <br class="clear" />

</div>