config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :topics do
    resources :posts
  end
  get '/votes/up', to: 'votes#up'
  get '/votes/down', to: 'votes#down'

  resources :comments, except: [:index]
  root to: 'topics#index'
  resources :favorites, only: [:create, :index, :destroy]
  get '/users/comments', to: 'users#comments'
  get '/users/posts', to: 'users#posts'

end

app/models/post.rb
# Post model
#
# == License
# Code is owned by Kari
# Fields include id, title, description, rank
# user_id, post_id, status, created_at, updated_at
class Post < ActiveRecord::Base
  attr_accessor :post_id, :image
  include Statusable
  belongs_to :topic
  belongs_to :user
  has_many :comments
  has_many :votes
  has_many :favorites
  validates :title, presence: true, length: { maximum: 255 }
  validates :description, presence: true,  length: { maximum: 65_535 }
  mount_uploader :image, ImageUploader
  # validates :rank, numericality: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :destroy, :edit, :update]
  before_action :authenticate_user!, only: [:new, :create, :destroy, :edit, :update]
  before_action :check_post_ownership, only: [:destroy, :edit, :update]

  def index
    # @topic = Topic.find(params[:topic_id])
    # @posts = Post.includes(:topic).active.order(created_at: :desc)
  end

  def new
    @post = Post.new
    @topic = Topic.find(params[:topic_id])
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    @topic = Topic.find(params[:topic_id])
    @post.topic_id = params[:topic_id]
    my_save(@post, topic_path(@post.topic))
  end

  def show
    comments = @post.comments.active
    @comments = comments.paginate(:page => params[:page], :per_page => 3)
    @comment = Comment.new post_id: @post.id
    @score = @post.votes.pluck(:value).compact.sum
  end

  def destroy
    my_destroy(@post, topic_path(@post.topic))
  end

  def edit
    @topic = Topic.find(params[:topic_id])
  end

  def update
    my_update(@post, post_params, topic_post_path(@post.topic, @post))
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :description, :image)
  end

  def check_post_ownership
    unless @post.user == current_user
      redirect_to new_user_session_path
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper

  def vote_link(post)
    return unless current_user
    return unless current_user.votes.where(post_id: post.id).empty?
    links = ''
    links += "<li class='button tiny success vote' >#{ link_to 'Up', votes_up_path(vote: { post_id: post.id }) }"
    links += "<li class='button tiny success vote' >#{ link_to 'Down', votes_down_path(vote: { post_id: post.id }) }"
    links.html_safe
  end

  def fav_link(post)
    return unless current_user
    return unless current_user.favorites.where(post_id: post.id).empty?

    "<div>#{ link_to "Add Post to Favorites", favorites_path(favorite: { post_id: post.id }), method: :post }</div>"
  end

  def crud_post(object)
    return unless object.user == current_user
    links = ''
    links += "<ul class='button-group [tiny secondary]'>"
    links += "<li class='button tiny secondary' >#{ link_to 'Edit', edit_topic_post_path(object.topic, object) }</li>"
    links += "<li class='button tiny secondary'>#{ link_to 'Destroy', [object.topic, object], method: :delete, data: {confirm: 'Are you sure?'}}</li>"
    links += "</ul>"
    links += fav_link(object).to_s

    links.html_safe
  end

  def new_comment(object)
    return unless current_user
    links = ''
    links << "#{link_to 'New Comment', new_comment_path(:post_id => object.id), id: 'new_comment_link', remote: true}"
    links.html_safe

  end


  def crud_comment(comment)
    return unless comment.user == current_user || comment.post.user == current_user
    "<li class='button tiny secondary'>#{ link_to 'delete', comment, method: :delete, data: {confirm: 'Are you sure?'} }</li>".html_safe
  end
end

app/views/posts/_form.html.erb
<%= red_error_box(@post) %>
<h3>New Post for <%= @topic.title %></h3>
<%= form_for [@topic, @post], :html => {:multipart => true} do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= f.label :description %>
<%= f.text_area :description %>
<%= f.file_field :image %>
<%= f.hidden_field :image_cache %>
<%= f.submit 'Save' %>
<% end %>

app/views/posts/edit.html.erb
<%= render partial: 'form' %>

app/views/posts/index.html.erb
<h2> Posts </h2>

<% @posts.each do |post| %>
<h4><%= post.topic.title %></h4>
<h3><%= "#{post.title} (#{post.created_at})" %></h3>
<h4><%= post.description %></h4>

<% end %>

<%= link_to "New Post", new_topic_post_path(@posts.topic) %>

app/views/posts/show.html.erb
<div class="row show-topics">
  <div class="small-10 small-centered columns">

    <div class="row">
        <div class="small-6 columns">
        <%= link_to @post.topic.title, topic_path(@post.topic) %>
        	<h2><%= @post.title %></h2><%= @post.rank.to_i %> Rank
          <div><%= image_tag @post.image_url.to_s %></div>
        	<td><%= @post.description %></td>
          <%= crud_post(@post) %>
          <%= vote_link(@post) %>
        </div>


        <div class="small-6 columns">
          <h5 id='comments_count'><%= pluralize(@comments.count, 'Comment') %></h5>
          <div class="comments" id="comment_scroll">
          <% @comments.each do |comment| %>
            <%= render partial: 'comments/comment', locals: { comment: comment } %>
          <% end %>
          <%= will_paginate @comments %>
          </div>

          <div style="border-top-style: dotted"></div>
            <h3>Add Comment</h3>
              <%= new_comment(@post) %>
          </div>
              <br class="clear" />
          </div>
        </div>
    </div>


  </div>
</div>